spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb

logging.level:
  com.sap: DEBUG
  org.springframework: ERROR
  org.springframework.security: DEBUG
  org.springframework.web: DEBUG
sap.security.services:
  identity:
    clientid:  sb-clientId!t0815  # SecurityTest.DEFAULT_CLIENT_ID
    domains:
      - localhost                 # SecurityTest.DEFAULT_DOMAIN
  xsuaa:
    xsappname: xsapp!t0815        # SecurityTest.DEFAULT_APP_ID
    uaadomain: localhost          # SecurityTest.DEFAULT_DOMAIN
    clientid:  sb-clientId!t0815  # SecurityTest.DEFAULT_CLIENT_ID
    url:       http://localhost   # SecurityTest.DEFAULT_URL