spring:
  datasource:
    url: jdbc:mysql://mysql.re-security.svc.cluster.local:3306/mysql
    username: admin
    password: P@ssword
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    show-sql: true